"use client";

import './globals.css';
import { Inter } from 'next/font/google';
import { Provider } from "react-redux";
import { store } from './store';
import { CheckAuth } from './checkAuth';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Hello</h1>

        <Provider store={store}>
          <CheckAuth>
            {children}
          </CheckAuth>
        </Provider>
      </body>
    </html>
  )
}
